# Generated by Django 5.2.5 on 2025-09-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0005_colorpalette_style_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated from content if empty', max_length=200)),
                ('content', models.TextField(help_text='The main note content')),
                ('category', models.CharField(choices=[('note', 'General Note'), ('bug', 'Bug Report'), ('todo', 'Task/Todo'), ('wishlist', 'Feature Idea'), ('code', 'Code Snippet'), ('reminder', 'Reminder'), ('question', 'Question')], default='note', help_text='Auto-detected based on content, can be manually overridden', max_length=20)),
                ('custom_tags', models.JSONField(blank=True, default=list, help_text='User-defined tags for additional organization')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notes appear at the top of lists')),
                ('is_code_snippet', models.BooleanField(default=False, help_text='Auto-detected or manually marked as code')),
                ('is_completed', models.BooleanField(default=False, help_text='For todo-type notes, mark as completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.TextField(blank=True, help_text='Computed search field for full-text search')),
                ('project', models.ForeignKey(blank=True, help_text='Optional project association for context', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bashvilleapi.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'project'], name='bashvilleap_user_id_d9fd63_idx'), models.Index(fields=['user', 'category'], name='bashvilleap_user_id_da056a_idx'), models.Index(fields=['user', 'is_pinned'], name='bashvilleap_user_id_a3169b_idx'), models.Index(fields=['created_at'], name='bashvilleap_created_193c06_idx')],
            },
        ),
    ]
