# Generated by Django 5.2.5 on 2025-09-22 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0006_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned', 'order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for drag and drop sorting within category'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'order'], name='bashvilleap_user_id_e79001_idx'),
        ),
    ]
