# Generated by Django 5.2.5 on 2025-09-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0007_alter_note_options_note_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive note'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Mark note as important'),
        ),
    ]
