# Generated by Django 5.2.5 on 2025-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0008_note_is_archived_note_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', help_text='Priority level for organization and visual indicators', max_length=10),
        ),
    ]
