# Generated by Django 5.2.5 on 2025-09-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0009_note_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='blocks',
            field=models.JSONField(default=list, help_text='Content blocks (text, checklist, code, etc.)'),
        ),
    ]
