# Generated by Django 5.2.5 on 2025-09-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashvilleapi', '0010_remove_note_content_note_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('note', 'General Note'), ('bug', 'Bug Report'), ('todo', 'Task/Todo'), ('wishlist', 'Feature Idea'), ('code', 'Code Snippet'), ('reminder', 'Reminder'), ('question', 'Question')], default='note', help_text='Auto-detected based on content', max_length=20),
        ),
    ]
